apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-lfyp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-lfyp
    app.kubernetes.io/part-of: integ-app-phin
  name: hacbs-test-project-lfyp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-lfyp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-lfyp
    spec:
      containers:
      - image: quay.io/rycole-appstudio/integration1-shiw-tenant/integ-app-phin/hacbs-test-project-lfyp@sha256:4777b9af470f08a4b8d18bd1f4181a4de0f81fb0e729559b8ae2fe762a980f51
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
